// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnaDuC9Nctsw-pVb8Je7zOkHByfbJmqck',
    appId: '1:597680370588:web:091631cc30249b3b930e59',
    messagingSenderId: '597680370588',
    projectId: 'my-portfolio-2ca93',
    authDomain: 'my-portfolio-2ca93.firebaseapp.com',
    storageBucket: 'my-portfolio-2ca93.firebasestorage.app',
    measurementId: 'G-JT5EP4RNEM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvXy8FHfd68Ub3uoYJ2RCAZORXTdONyAk',
    appId: '1:597680370588:android:18d104238e28f551930e59',
    messagingSenderId: '597680370588',
    projectId: 'my-portfolio-2ca93',
    storageBucket: 'my-portfolio-2ca93.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXanPx1pI2-aZuuUJqnCj0zJRawm8FQwE',
    appId: '1:597680370588:ios:3fa10262e96377b4930e59',
    messagingSenderId: '597680370588',
    projectId: 'my-portfolio-2ca93',
    storageBucket: 'my-portfolio-2ca93.firebasestorage.app',
    iosBundleId: 'com.example.flutterPortfolio',
  );
}
